version: '3'
services:


  mongodb:
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - mongo-net
    volumes:
      - mongo-data= /data/db
    image: mongo
    container_name: mongodb


  mongo-web:
    ports:
      - "8081:8081"
    restart: always
    networks:
      - mongo-net
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    container_name: mongo-web
    image: mongo-express
    depends_on:
      - mongodb

  todo-api:
    ports:
      - "8080:8080"
    networks:
      - mongo-net
    environment:
      - spring.data.mongodb.host=mongodb
    image: bhaskar150/todo-apiimage:1.0
    container_name: todo-api
    depends_on:
      - mongodb

networks:
  mongo-net:

volumes:
  mongo-data:

    


     
